name: E2E Tests
env:
  TESTING_ENV: ${{ secrets.TESTING_ENV }}

on:
  pull_request:
    branches:
      - 'main'
    types: [ opened, synchronize, reopened, ready_for_review ]
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v3
          if: success()

      -   name: Setup PHP with coverage driver
          uses: shivammathur/setup-php@v2
          with:
            php-version: 8.2
            coverage: pcov

      -   name: Setup
          if: success()
          run: |
            sudo service mysql start
            php -v
            mysql -uroot -proot -e "CREATE DATABASE docking;"
            composer install --no-interaction
            echo "$TESTING_ENV" > .env
            php artisan key:generate
            php artisan optimize
            php artisan storage:link

      -   name: Setup WkHTMLToPdf
          if: success()
          run: sudo apt-get update && sudo apt-get install wkhtmltopdf -y

      -   name: PHPUnit tests - E2E Suite
          if: success()
          run: |
            composer test-e2e
